//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTARIO.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEFACTURAS
    {
        public DETALLEFACTURAS()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public int id_detalle { get; set; }
        public int Id_articulos { get; set; }
        public int Monto { get; set; }
        public int Cantidad { get; set; }
        public int Id_cliente { get; set; }
        public Nullable<int> Descuento { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        public virtual CLIENTES CLIENTES1 { get; set; }
        public virtual FACTURAS FACTURAS1 { get; set; }
    }
}
